apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dep12-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.local
      http:
        paths:
          - path: /one
            pathType: Prefix
            backend:
              service:
                name: one-service
                port:
                  number: 80
          - path: /two
            pathType: Prefix
            backend:
              service:
                name: two-service
                port:
                  number: 80
